-- Progression Service: Season Promotion Reward Claims 테이블
-- 시즌 프로모션 보상 수령 기록
--
-- ## 보상 타입
-- - BASIC: 기본 보상 (모든 유저)
-- - VIP_BONUS: VIP 보너스 (VIP 유저만)
--
-- ## 수령 제약
-- - UNIQUE(user_public_id, promotion_id, step, reward_type)
-- - 같은 스텝의 기본 보상과 VIP 보너스를 별도로 수령

CREATE TABLE IF NOT EXISTS season_promotion_reward_claims
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'Internal PK (Auto-increment)',
    public_id      VARCHAR(20)  NOT NULL UNIQUE COMMENT 'Public ID (Snowflake ID - Base62)',
    user_public_id VARCHAR(20)  NOT NULL COMMENT 'User Public ID (다른 서비스의 User)',
    promotion_id   VARCHAR(50)  NOT NULL COMMENT 'Season Promotion ID',
    step           INT          NOT NULL COMMENT '스텝 번호',
    reward_type    VARCHAR(50)  NOT NULL COMMENT '보상 타입 (BASIC, VIP_BONUS)',
    reward_amount  INT          NOT NULL COMMENT '보상 금액',
    claimed_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수령 일시',
    -- AbsDomain
    created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_promotion_step_reward (user_public_id, promotion_id, step, reward_type) COMMENT '1유저 1스텝 1보상타입 1회 제약',
    INDEX idx_reward_claim_public_id (public_id),
    INDEX idx_reward_claim_user (user_public_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci
  COMMENT = '시즌 프로모션 보상 수령 기록 (기본/VIP 보너스)';
