-- Progression Service: User Season Promotion Progress 테이블
-- 사용자별 시즌 프로모션 진행도 (배틀패스)
--
-- ## 시즌 프로모션 특징
-- - Step 기반 진행 (1 → maxStep)
-- - 2-track 보상: 기본 보상 + VIP 보너스
-- - Customer/Rider 모두 지원
-- - 기간 제한 (season_promotions.csv의 start_at ~ end_at)
--
-- ## 상태
-- - IN_PROGRESS: 진행 중
-- - COMPLETED: 최종 스텝 완료

CREATE TABLE IF NOT EXISTS user_season_promotion_progress
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'Internal PK (Auto-increment)',
    public_id        VARCHAR(20)  NOT NULL UNIQUE COMMENT 'Public ID (Snowflake ID - Base62)',
    user_public_id   VARCHAR(20)  NOT NULL COMMENT 'User Public ID (다른 서비스의 User)',
    promotion_id     VARCHAR(50)  NOT NULL COMMENT 'Season Promotion ID (season_promotions.csv)',
    current_step     INT          NOT NULL DEFAULT 0 COMMENT '현재 스텝',
    current_progress INT          NOT NULL DEFAULT 0 COMMENT '현재 스텝 내 진행도',
    is_vip           BOOLEAN      NOT NULL DEFAULT FALSE COMMENT 'VIP 여부 (VIP 보너스 수령 가능)',
    status           VARCHAR(50)  NOT NULL COMMENT '상태 (IN_PROGRESS, COMPLETED)',
    completed_at     DATETIME COMMENT '완료 일시 (maxStep 도달)',
    -- AbsDomain
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_promotion (user_public_id, promotion_id) COMMENT '1유저 1시즌 1회 제약',
    INDEX idx_user_promotion_public_id (public_id),
    INDEX idx_user_promotion_user (user_public_id),
    INDEX idx_user_promotion_status (status)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci
  COMMENT = '사용자별 시즌 프로모션 진행도 (배틀패스)';
