-- Progression Service: User Quota Progress 테이블
-- 사용자별 할당량 진행도 (주간/월간 미션)
--
-- ## Quota 타입
-- - ACTION_CONSTRAINT: 제약 (예: 주간 3회까지만 가능)
-- - ACTION_REWARD: 보상 (예: 주간 3회 달성 시 포인트 지급)
--
-- ## Cycle 관리
-- - WEEKLY: 주간 (매주 월요일 00:00 리셋)
-- - MONTHLY: 월간 (매월 1일 00:00 리셋)
-- - cycle_key: YYYY-WW 또는 YYYY-MM (예: 2025-W06, 2025-03)
--
-- ## 상태
-- - IN_PROGRESS: 진행 중
-- - COMPLETED: 완료 (maxLimit 도달)
-- - CLAIMED: 보상 수령 완료 (ACTION_REWARD만)

CREATE TABLE IF NOT EXISTS user_quota_progress
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'Internal PK (Auto-increment)',
    public_id        VARCHAR(20)  NOT NULL UNIQUE COMMENT 'Public ID (Snowflake ID - Base62)',
    user_public_id   VARCHAR(20)  NOT NULL COMMENT 'User Public ID (다른 서비스의 User)',
    quota_key        VARCHAR(100) NOT NULL COMMENT 'Quota Key (quotas.csv의 quota_key)',
    cycle_key        VARCHAR(20)  NOT NULL COMMENT 'Cycle Key (YYYY-WW 또는 YYYY-MM)',
    current_progress INT          NOT NULL DEFAULT 0 COMMENT '현재 진행도',
    status           VARCHAR(50)  NOT NULL COMMENT '상태 (IN_PROGRESS, COMPLETED, CLAIMED)',
    completed_at     DATETIME COMMENT '완료 일시',
    claimed_at       DATETIME COMMENT '보상 수령 일시 (ACTION_REWARD만)',
    -- AbsDomain
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_quota_cycle (user_public_id, quota_key, cycle_key) COMMENT '1유저 1할당량 1주기 1회 제약',
    INDEX idx_user_quota_public_id (public_id),
    INDEX idx_user_quota_user (user_public_id),
    INDEX idx_user_quota_cycle (cycle_key),
    INDEX idx_user_quota_status (status)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci
  COMMENT = '사용자별 할당량 진행도 (주간/월간 미션)';
