-- Progression Service: User Archive Progress 테이블
-- 사용자별 업적 진행도
--
-- ## 진행도 추적
-- - EVENT_BASED: 이벤트 발생 시 자동 진행 (Kafka Consumer)
-- - STAT_BASED: 통계 기반 수동 진행 (일괄 배치)
--
-- ## 상태
-- - IN_PROGRESS: 진행 중
-- - COMPLETED: 완료 (조건 충족)
-- - CLAIMED: 보상 수령 완료

CREATE TABLE IF NOT EXISTS user_archive_progress
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'Internal PK (Auto-increment)',
    public_id        VARCHAR(20)  NOT NULL UNIQUE COMMENT 'Public ID (Snowflake ID - Base62)',
    user_public_id   VARCHAR(20)  NOT NULL COMMENT 'User Public ID (다른 서비스의 User)',
    archive_id       VARCHAR(50)  NOT NULL COMMENT 'Archive Master ID',
    current_progress INT          NOT NULL DEFAULT 0 COMMENT '현재 진행도',
    status           VARCHAR(50)  NOT NULL COMMENT '상태 (IN_PROGRESS, COMPLETED, CLAIMED)',
    completed_at     DATETIME COMMENT '완료 일시',
    claimed_at       DATETIME COMMENT '보상 수령 일시',
    -- AbsDomain
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_archive (user_public_id, archive_id) COMMENT '1유저 1업적 1회 제약',
    INDEX idx_user_archive_public_id (public_id),
    INDEX idx_user_archive_user (user_public_id),
    INDEX idx_user_archive_status (status)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci
  COMMENT = '사용자별 업적 진행도 (이벤트/통계 기반)';
