{
 "title": "Kafka Metrics",
 "tags": [ "kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Producer - Records Sent/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total[1m])",
     "legendFormat": "{{service}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer - Records Consumed/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_records_consumed_total[1m])",
     "legendFormat": "{{service}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer - Lag (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_max",
     "legendFormat": "{{service}} - {{topic}} - {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Producer - Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_error_total[1m])",
     "legendFormat": "{{service}} - {{topic}}"
    }
   ]
  }
 ]
}