DROP TABLE IF EXISTS `payment_processes`;
CREATE TABLE payment_processes (
                                  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'Internal PK (Auto-increment)',
                                  public_id VARCHAR(20) NOT NULL COMMENT 'Public ID (Snowflake ID - Base62)',
                                  order_public_id VARCHAR(20) DEFAULT NULL COMMENT 'E-commerce Service의 Order Public ID (외부 거래는 NULL)',
                                  user_keycloak_id VARCHAR(100) NOT NULL COMMENT 'User의 Keycloak Subject ID',
                                  order_number VARCHAR(255) NULL COMMENT '주문 번호',
                                  provider VARCHAR(50) DEFAULT NULL COMMENT 'PG사 이름 (외부 거래는 NULL)',
                                  cash_gateway_mid VARCHAR(100) NOT NULL COMMENT 'Cash Gateway MID (Cash Gateway가 발급한 가맹점 식별자)',
                                  amount DECIMAL(15,3) NOT NULL COMMENT '결제 요청 금액',
                                  request_payload JSON NULL COMMENT '요청 바디 (PG사로 보낸 원문, 외부 거래는 NULL)',
                                  response_payload JSON NULL COMMENT '응답 바디 (PG사에서 받은 원문)',
                                  status VARCHAR(20) NOT NULL COMMENT '결제 상태',
                                  origin_process_id BIGINT(20) DEFAULT NULL COMMENT '원 결제 프로세스 ID (취소인 경우 참조)',
                                  gateway_reference_id VARCHAR(255) NOT NULL COMMENT 'Cash Gateway 고유 거래 식별자 (CGW_XXX)',
                                  code VARCHAR(10) NULL COMMENT 'PG사 응답 코드 (예: 0000, E5000 등)',
                                  message VARCHAR(255) NULL COMMENT '응답 메시지 혹은 에러 메시지',
                                  pg_transaction VARCHAR(100) NULL COMMENT 'PG사 거래 아이디',
                                  pg_approval_no VARCHAR(100) NULL COMMENT 'PG사 승인번호',
                                  active_request_key VARCHAR(100) NULL COMMENT '활성화된 요청 키 (UNKNOWN 상태일 때만 존재, 중복 방지)',
                                  origin_source VARCHAR(100) NOT NULL COMMENT '거래 출처 (예: ECOMMERCE, PARTNER_A, PARTNER_B)',
                                  requested_at DATETIME NULL COMMENT 'PG 요청 시작 시각 (폴링 서비스가 PG로 요청을 전송한 시각)',
                                  ack_received_at DATETIME NULL COMMENT 'PG 승인 응답 시각 (202 Accepted or 200 OK를 받은 시각)',
                                  last_request_attempt_at DATETIME NULL COMMENT '마지막 재시도 시각',
                                  request_attempt_count INT DEFAULT 0 COMMENT '총 요청 시도 횟수',
                                  last_http_status_code VARCHAR(10) NULL COMMENT '마지막 PG HTTP 상태 코드 (202, 200, 400 등)',
                                  is_external BOOLEAN GENERATED ALWAYS AS (order_public_id IS NULL) STORED COMMENT '외부 거래 여부 (order_public_id가 NULL이면 외부 거래)',
                                  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
                                  modified_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
                                  PRIMARY KEY (id),
                                  UNIQUE KEY idx_payment_processes_public_id (public_id),
                                  KEY idx_payment_processes_order_public_id (order_public_id),
                                  KEY idx_payment_processes_user_keycloak_id (user_keycloak_id),
                                  KEY idx_provider_cgw_mid_status (provider, cash_gateway_mid, status),
                                  KEY idx_status_created (status, created_at),
                                  KEY idx_pg_transaction (pg_transaction),
                                  UNIQUE KEY uq_payment_processes_unique (provider, pg_transaction, pg_approval_no, origin_process_id),
                                  UNIQUE KEY uq_active_request (active_request_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;